name: auto-commit

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

jobs:
  auto-commit-formatter:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'bug') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/*.{lua}
            !**/*.yml
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Install stylua
        run: |
          wget https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.0/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
      - name: Format changed files with StyLua
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              ./stylua "$file"
          done
      - name: Commit and push changes files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply lua style
