name: formatter-prettier

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'bug') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/*.{js,html,css}
            !**/*.yml
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Get file extensions
        id: getext
        run: |
          import os
          files = '${{ steps.changed-files.outputs.all_changed_files }}'.split()
          extensions = set('*' + os.path.splitext(file)[1] for file in files)
          with open(os.getenv('GITHUB_ENV'), 'a') as f:
            f.write(f"CHANGED_EXTENSIONS={' '.join(extensions)}\n")
        shell: python
      - name: Install Node.js and Prettier
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install --global prettier
      - name: Format changed files with Prettier
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              prettier --write "$file"
          done
      - name: Commit changed files and push current branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply html,css,js formated code
          file_pattern: ${{ env.CHANGED_EXTENSIONS }}
          status_options: '--untracked-files=no'
