name: formatter-lua

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'bug') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/*.{js,html,css,lua}
            !**/*.yml
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Install stylua
        run: |
          wget https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.0/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
      - name: Format changed files with StyLua
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              ./stylua "$file"
          done
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git config --global push.default current
          if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [ -f "$file" ]; then
                git add "$file"
              fi
            done
      - name: Push changes
        if: steps.changed_files.outputs.files_changed == 'true' && github.event_name == 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
