name: formatter

on:
  push:
    branches: [ main ]

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stylua
      - name: Install stylua
        run: |
          wget https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.0/stylua-linux-aarch64.zip
          unzip stylua-linux-aarch64.zip
          chmod +x stylua
      - name: Format changed files
        run: |
          git fetch origin ${{ github.base_ref }}
          changed_files=$(git diff --name-only --diff-filter=AM origin/${{ github.base_ref }}..${{ github.sha }} '*.lua')
          for file in $changed_files; do
            if [ -f "$file" ]; then
              ./stylua "$file"
            fi
          done
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Format Lua code with stylua" || echo "No changes to commit"
          git push
