name: formatter

on:
  push:
    branches: [ main ]

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - uses: actions/checkout@v3
      - name: Install stylua
        run: |
          wget https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.0/stylua-linux-aarch64.zip
          unzip stylua-linux-aarch64.zip
          chmod +x stylua
      - name: Format changed files
        run: |
          changed_files=${{ steps.changed-files.outputs.all_changed_files }}
          for file in $changed_files; do
              ./stylua "new.lua"
          done
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          changed_files=${{ steps.changed-files.outputs.all_changed_files }}
          for file in $changed_files; do
            if [ -f "$file" ]; then
              git add "$file"
            fi
          done
          git commit -m "Format Lua code"
          git push origin main
