name: formatter

on:
  push:
    branches: [ main ]

jobs:
    formatter:
     name: formatter
     runs-on: ubuntu-latest
     
 steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         version: latest
         args: --check .

